name: Run Tests on Compose Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Test with Docker Compose
        run: |
          cd ./src/ansiblevault;
            docker-compose -f docker-compose.yml up --build --abort-on-container-exit
            docker-compose -f docker-compose.yml down
          cd ../pgadmin-postgres-proxy-hasura;
            docker-compose -f docker-compose.yml up --build --abort-on-container-exit
            docker-compose -f docker-compose.yml down
          cd ../timescale-hasura;
            docker-compose -f docker-compose.yml up --build --abort-on-container-exit
            docker-compose -f docker-compose.yml down